### ISSUE TITLE
Show descriptions

### ISSUE THREAD

**Issue by 3nt3** [chaosdorf/freitagsfoo-infobeamer#5]
We want to be able to display descriptions of talks.

They are already in the JSON we get (there's a `description` key in every talk object that contains a plain text description we can use).

We'd need to add a new sub-node that displays the title of the talk and the description (or maybe two sub-nodes?). It / they should be able to receive the index of the talk to display via UDP.

Also, we need to update the main node to include animations to enter and leave this new state.

Finally, we'd need to add code to freitagsfoo-web to trigger this new state, but that's outside the scope of this issue.

**Comment by YtvwlD** [comment]
This works since dd633154a4ba06e6f9b12dbd08d10d1a06cd537a.
